### ISSUE TITLE
Proposal - Homepage Layout for v1.0.1

### ISSUE THREAD

**Issue by bassettsj** [NEU-Libraries/scholar-onesearch#46]
Proposing a change in homepage layout:
![screen shot 2013-06-15 at 10 33 46 am](https://f.cloud.github.com/assets/1218420/658226/a05432e2-d5c8-11e2-8f63-416c926f66b1.png)

To:

![screen shot 2013-06-15 at 10 21 59 am](https://f.cloud.github.com/assets/1218420/658227/aeb56b80-d5c8-11e2-8ce3-0a7b4ddaa7a2.png)
![screen shot 2013-06-15 at 10 21 56 am](https://f.cloud.github.com/assets/1218420/658228/aec17808-d5c8-11e2-98cb-2bf68d270db1.png)
![screen shot 2013-06-15 at 10 21 39 am](https://f.cloud.github.com/assets/1218420/658230/aec7f9a8-d5c8-11e2-95ff-981dc2857f22.png)
![screen shot 2013-06-15 at 10 21 31 am](https://f.cloud.github.com/assets/1218420/658229/aec81e60-d5c8-11e2-8026-4267c5ff329f.png)

My notes

``` css
.EXLHomeNewsContainer i{
    color: #2c3e50;
    text-align: center;
    display: block;
    margin: 0 auto;

    width: 1.5em;
    height: 1.5em;
}

#exlidHomeContainer div.EXLHomeBlockContainer1 div.EXLContentBlock1,
#exlidHomeContainer div.EXLHomeBlockContainer1 div.EXLContentBlock2{
    width:100% !important
}
```

``` html
<div class="EXLHomeNewsContainer row">
<div class="col col-lg-4">
  <i class="icon-question  icon-4x icon-border"></i>
  <h3>How does this work?</h3>
    <p>
      Scholar OneSearch provides simple, one-stop searching for books, articles, digital media, and more. Local Northeastern collections and global resources can all be discovered through Scholar OneSearch, with many items available in full text online.
    </p>
    <p>
      Scholar OneSearch also helps you manage your research: renew books and videos, create lists, export citations to Refworks and Endnote Web, and order materials from other libraries. Be sure to sign in with your myNEU credentials to view full search results--some databases, like Web of Science, only show results when you’re signed in.
    </p>
    <p>
      Questions? Comments?<br>
      <a href="http://library.northeastern.edu/about/contact_us/">Let us know what you think! </a>
    </p>
</div>
<div class="col col-lg-4">
  <i class="icon-search  icon-4x  icon-border"></i>
  <h3>What happened to NUCat?</h3>
    <p>
      Scholar OneSearch indexes all of the books, e-books, videos, journals, and other collections from our legacy catalog, NUCat, with the option to search and retrieve more, including articles, proceedings, and digital materials.
    </p>
    <p>
      Limit your search by choosing “Library Collections” from the drop-down above to find print materials held at Snell Library, the Law Library, and the African American Institute.
    </p>
</div>
<div class="col col-lg-4">
    <i class="icon-comments-alt  icon-4x  icon-border"></i>
    <h3>Need help getting started? Not finding what you’re looking for?</h3>
    <p>
      <a href="http://library.northeastern.edu/ask">Ask a librarian how to start your search</a>, or dig deeper into library resources with <a href="http://subjectguides.lib.neu.edu/browse.php">dedicated subject guides</a>, which offer advice, recommendations, and subject librarians to contact for help on research in your discipline.
    </p>
</div>
</div>
```
